# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88cc625fff3e8354c41c93e134e80d36dbd0beb39f827cab8f2829113c8b3a3a7023a9831c73e60f5e647e4e5db16911cb599b9b55cc372850cd5856740d32a4

test:
  secret_key_base: b270aea3a33315ca7392a11e613b593b3a9fb3b3529fcf267eb7c4e0f29c4d8ee1e7e900b4798c3efb1c07c65c3159b18c744d9bf782b5098ff08f7b856ec099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
